services:
  services:
  vpn-gateway:
    image: ama15/openvpn-wg-gateway:tcp
    container_name: vpn-gateway
    privileged: true
    environment:
      - VPN_PUBLIC_HOST=THEIR_PUBLIC_IP_OR_DNS
    volumes:
      - ./vpn-data:/vpn-data
      - ./openvpn:/etc/openvpn
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf:ro
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
